services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: app_sabana
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: gunicorn --worker-class=gevent --worker-connections=1000 --workers=3 -t 240 app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
